name: auth
description: Firebase Auth と Cloud Functions を用いた認証実装
version: 0.0.1
publish_to: "none"

environment:
  sdk: ^3.10.3

resolution: workspace

dependencies:
  cloud_functions: ^6.0.6
  firebase_auth: ^6.1.4
  flutter:
    sdk: flutter

dev_dependencies:
  altive_lints: ^2.1.0
  flutter_test:
    sdk: flutter

flutter: {}
