name: auth
description: 認証抽象（Authenticator）と Firebase 実装
version: 0.0.1
publish_to: "none"

environment:
  sdk: ^3.10.3

resolution: workspace

dependencies:
  cloud_firestore: ^6.1.2
  firebase_auth: ^6.1.4
  flutter:
    sdk: flutter

dev_dependencies:
  altive_lints: ^2.1.0
  flutter_test:
    sdk: flutter

flutter: {}
