// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkzA_UEnwhradGYAEGKaY44tg1n2n5c_k',
    appId: '1:908859080638:web:b243252e53914a3ac343ef',
    messagingSenderId: '908859080638',
    projectId: 'kaimono-plus',
    authDomain: 'kaimono-plus.firebaseapp.com',
    storageBucket: 'kaimono-plus.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaeG2n3t6W4SxptGx3xcH4VZsJ8xE4pz4',
    appId: '1:908859080638:android:3d22dafbcfcd032cc343ef',
    messagingSenderId: '908859080638',
    projectId: 'kaimono-plus',
    storageBucket: 'kaimono-plus.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUSTsvALAuqXKx6o14Kv-zB9eUeG7oabI',
    appId: '1:908859080638:ios:a714f5e9e873a7a8c343ef',
    messagingSenderId: '908859080638',
    projectId: 'kaimono-plus',
    storageBucket: 'kaimono-plus.firebasestorage.app',
    iosBundleId: 'com.example.kaimonoPlus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUSTsvALAuqXKx6o14Kv-zB9eUeG7oabI',
    appId: '1:908859080638:ios:a714f5e9e873a7a8c343ef',
    messagingSenderId: '908859080638',
    projectId: 'kaimono-plus',
    storageBucket: 'kaimono-plus.firebasestorage.app',
    iosBundleId: 'com.example.kaimonoPlus',
  );

}